config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :roles
  end

  namespace :admin do
  get 'administer/index'
  end

  root to: 'visitors#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :users do
    collection do
      get 'view_locked'
    end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/role.rb
class Admin::Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/admin/roles_users.rb
class Admin::RolesUsers < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :admin_roles, :class_name => 'Admin::Role'
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  after_initialize :set_default_role,             :if => :new_record?
  after_initialize :set_default_failed_attempts,  :if => :new_record?

  def set_default_role
    self.admin_roles ||= :user
  end

  def set_default_failed_attempts
    self.failed_attempts ||= 0
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :lockable

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def admin?
    self.admin_roles.include?(Admin::Role.find(3))
  end

end

app/controllers/admin/administer_controller.rb
class Admin::AdministerController < ApplicationController
  before_filter :find_controller

  def index

  end

  private

  def find_controller
    @controller = params[:controller].slice(0..(params[:controller].index('/'))-1)
    @p = 2
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
  before_action :set_admin_role, only: [:show, :edit, :update, :destroy]
  before_filter :find_controller

  # GET /admin/roles
  # GET /admin/roles.json
  def index
    @admin_roles = Admin::Role.all
  end

  # GET /admin/roles/1
  # GET /admin/roles/1.json
  def show
  end

  # GET /admin/roles/new
  def new
    @admin_role = Admin::Role.new
  end

  # GET /admin/roles/1/edit
  def edit
  end

  # POST /admin/roles
  # POST /admin/roles.json
  def create
    @admin_role = Admin::Role.new(admin_role_params)

    respond_to do |format|
      if @admin_role.save
        format.html { redirect_to @admin_role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @admin_role }
      else
        format.html { render :new }
        format.json { render json: @admin_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/roles/1
  # PATCH/PUT /admin/roles/1.json
  def update
    respond_to do |format|
      if @admin_role.update(admin_role_params)
        format.html { redirect_to @admin_role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_role }
      else
        format.html { render :edit }
        format.json { render json: @admin_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/roles/1
  # DELETE /admin/roles/1.json
  def destroy
    @admin_role.destroy
    respond_to do |format|
      format.html { redirect_to admin_roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_role
      @admin_role = Admin::Role.find(params[:id])
      if !current_user.admin?
        redirect_to root_path, :alert => "Your role can't do it."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_role_params
      params.require(:admin_role).permit(:name)
    end

    # To find the root controller.
    def find_controller
      @controller = params[:controller].slice(0..(params[:controller].index('/'))-1)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ## Use to discover the class User methods
  ## @methods_list = current_user.methods - Object.methods
  ## puts "\n\current_user.methods : "+ @methods_list.sort.join("\n").to_s+"\n\n"
  ## Don't cancel if it's not important

  before_filter :authenticate_user!
  before_filter :find_controller
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def view_locked
    @users = User.where.not(locked_at: nil)
    authorize User
    if @users.nil?
      redirect_to admin_administer_index_path, :warning => "None blocked User."
    end
  end

  def new
    @user = User.new
    authorize User
  end

  def create
    @user = User.new(secure_params)
    authorize @user
    @back = request.env["HTTP_REFERER"]
    @here = request.env["REQUEST_URI"]
    if @user.save
      redirect_to admin_administer_index_path, :notice => "User updated."
    else
      if !request.env["HTTP_REFERER"].blank? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
        redirect_to :back, :alert => "Unable to create user."
      else
        redirect_to new_user_path, :alert => "Unable to create user."
      end
    end

  end

  def show
    @user = User.find_by_id(params[:id])
    if @user
      authorize @user
    else
      authorize current_user
      if !request.env["HTTP_REFERER"].blank? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
        redirect_to :back, :alert => "Unable to find this user."
      else
        redirect_to root_path, :alert => "Unable to find this user."
      end
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    if @user
      authorize @user
    else
      authorize current_user
      if !request.env["HTTP_REFERER"].blank? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
        redirect_to :back, :alert => "Unable to find this user."
      else
        redirect_to root_path, :warning => "Unable to find this user."
      end
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    authorize @user
    if current_user.admin?
      params[:user].delete(:current_password)
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      if params[:user][:locked_at] == 'LockNOW'
        params[:user][:locked_at] = Time.now
        params[:user][:failed_attempts] = 5
      elsif params[:user][:locked_at].blank?
        params[:user][:failed_attempts] = 0
      end
      if @user.update_without_password(secure_params)
        redirect_to admin_administer_index_path, :notice => "User updated."
      else
        redirect_to admin_administer_index_path, :alert => "Unable to update user."
      end
    else
      if @user.update_with_password(super_secure_params)
        redirect_to root_path, :notice => "User updated."
      else
        redirect_to root_path, :alert => "Unable to update user."
      end
    end
  end

  def destroy
    user = User.find_by_id(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit({:admin_role_ids => []}, :email, :password, :password_confirmation,
                                  :username, :name, :locked_at, :failed_attempts)
    ##params.require(:user).permit(:admin_role_ids => [])
  end

  def super_secure_params
    params.require(:user).permit(:role, :email, :password, :password_confirmation, :current_password, :username, :name)
  end

  def find_controller
    @controller = params[:controller]
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/admin/administer_helper.rb
module Admin::AdministerHelper
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/administer/_admin_nav.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Admin BAR</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Nuovo Utente', new_user_path %></li>
            <li><%= link_to 'Lista Utenti', users_path %></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><%= link_to 'Lista Utenti bloccati', view_locked_users_path %></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Roles <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Nuovo Ruolo', new_admin_role_path %></li>
            <li><%= link_to 'Lista Ruoli', admin_roles_path %></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>

app/views/admin/administer/index.html.erb
<h1>Admin::Administer#index</h1>
<p>Find me in app/views/admin/administer/index.html.erb</p>
<p><%= controller.controller_name %></p>

app/views/admin/roles/_form.html.erb
<%= form_for(@admin_role) do |f| %>
  <% if @admin_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_role.errors.count, "error") %> prohibited this admin_role from being saved:</h2>

      <ul>
      <% @admin_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'Create', :class => 'button right' %>

<% end %>

app/views/admin/roles/edit.html.erb
<div class="authform">
  <h3>Edit <%= @admin_role.name if @admin_role.name %></h3>

  <%= render 'form' %>

</div>

app/views/admin/roles/index.html.erb
<div class="container">
  <div class="row">
    <h3>Roles</h3>
      <div class="column">
        <table class="table">
          <thead>
          <tr>
            <th>Name</th>
            <th colspan="3">Action</th>
            <th></th>
            <th></th>

          </tr>
          </thead>
          <tbody>
          <% @admin_roles.each do |admin_role| %>
              <tr>
                <td><%= admin_role.name %></td>
                <td></td>
                <td></td>
                <td></td>
                <td><%= link_to 'Edit', edit_admin_role_path(admin_role), :class => 'button-xs' %></td>
                <td>
                    <%= link_to 'Destroy', admin_role, method: :delete, :data => { :confirm => "Are you sure?" },
                                :class => 'button-xs btn-danger' %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/admin/roles/new.html.erb
<div class="authform">
  <h3>Nuovo Ruolo <%= @admin_role.name if @admin_role.name %></h3>

  <%= render 'form' %>

  <%= link_to 'Back', admin_roles_path, :class => 'button left' %>

</div>

app/views/admin/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @admin_role.name %>
</p>

<%= link_to 'Edit', edit_admin_role_path(@admin_role) %> |
<%= link_to 'Back', admin_roles_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links_left' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</div>

app/views/layouts/_navigation_links_left.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Section_ONE' %></li>
  <li><%= link_to 'Section_TWO' %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Self-distruction' %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation_links_right.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Log out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to current_user.name, edit_user_path(current_user) %> </li>
<% else %>
  <li><%= link_to 'Log in', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', admin_administer_index_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Devise Pundit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Devise Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>

    </header>
    <main role="main">
      <% if user_signed_in? %>
          <% if current_user.admin? %>
              <% if @controller == 'admin' || controller.controller_name == 'users' %>
                  <%= render 'admin/administer/admin_nav' %>
              <% end %>
          <% end %>
      <% end %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td>
  <%= link_to user.name, user %>
</td>
<td>
  <%= link_to("Edit", edit_user_path(user), :class => 'button-xs') %>
</td>
<td>
  <%= user.admin_roles.map {|c| c.name}.join(', ') %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete,
              :class => 'button-xs btn-danger') unless user == current_user %>
</td>

app/views/users/edit.html.erb
<div class="authform">
  <h3>Edit <%= @user.name if @user.name %></h3>
  <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
    </div>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>
      </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <fieldset>
      <p>Leave these fields blank if you don't want to change your password.</p>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :autocomplete => 'off', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </fieldset>
    <fieldset>
      <% if !current_user.admin? %>
        <p>You must enter your current password to make changes.</p>
        <div class="form-group">
          <%= f.label :current_password %>
          <%= f.password_field :current_password, class: 'form-control' %>
        </div>
      <% else %>
        <p>Select the user roles.</p>
        <div class="form-group">
          <%= f.collection_check_boxes :admin_role_ids, Admin::Role.all, :id, :name do |b| %>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="input-group">
                         <span class="input-group-addon">
                            <!-- <input type="checkbox"> -->
                            <%= b.check_box %>
                         </span>
                        <span class="input-group-addon">
                            <%= b.label %>
                        </span>

                        <!-- <input type="text" class="form-control"> -->
                      </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                  </div><!-- /.row -->
          <% end %>
        </div>
      <% end %>
    </fieldset>
    <fieldset>
      <% if current_user.admin? %>
          <p>Blank unlocked - Locked user from date.</p>
          <div class="form-group">
            <%= f.label :locked_at %>
            <%= f.text_field :locked_at, class: 'form-control' %>
          </div>
        <% end %>
      </fieldset>
    <%= f.submit 'Update', :class => 'button right' %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="authform">
  <h3>Nuovo utente <%= @user.name if @user.name %></h3>
  <%= form_for @user do |f| %>

      <div class="form-group">
        <%= f.label :full_name %>
        <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :autocomplete => 'off', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Create', :class => 'button right' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/users/view_locked.erb
<div class="container">
  <div class="row">
    <h3>Locked Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>